-- 重构数据库结构以匹配代码中的 Types 定义
-- 注意：此脚本不会删除 'app_secrets' 表，也不会删除现有数据（除非手动清空）

-- ==========================================
-- 1. Tasks 表 (对应 types/app.ts 中的 Task 接口)
-- ==========================================

-- 确保表存在
CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- 逐个添加缺失的列 (如果是新表，这些也会被执行，如果列已存在则跳过)
-- title: string
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS title text;
-- description?: string
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS description text;
-- status: TaskStatus ('pending' | 'in_progress' | 'completed')
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
-- estimated_duration?: number (Seconds)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS estimated_duration integer DEFAULT 0;
-- actual_duration: number (Seconds)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS actual_duration integer DEFAULT 0;
-- start_time?: string | null (ISOString -> timestamptz)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS start_time timestamptz;
-- updated_at?: string
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT timezone('utc'::text, now());
-- is_course?: boolean
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS is_course boolean DEFAULT false;
-- location?: string
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS location text;
-- color?: string
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS color text;
-- is_deadline?: boolean
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS is_deadline boolean DEFAULT false;

-- ==========================================
-- 2. Courses 表 (对应 types/app.ts 中的 Course 接口)
-- ==========================================

-- 确保表存在
CREATE TABLE IF NOT EXISTS public.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- name: string
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS name text;
-- location: string
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS location text;
-- day_of_week: number (1-7)
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS day_of_week integer;
-- start_time: string ("HH:mm")
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS start_time text;
-- end_time: string ("HH:mm")
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS end_time text;
-- color?: string
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS color text;

-- ==========================================
-- 3. 安全策略 (RLS)
-- ==========================================

-- 启用 RLS
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- 清除旧策略 (防止重复)
DROP POLICY IF EXISTS "Users can view their own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can insert their own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can update their own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can delete their own tasks" ON public.tasks;

DROP POLICY IF EXISTS "Users can view their own courses" ON public.courses;
DROP POLICY IF EXISTS "Users can insert their own courses" ON public.courses;
DROP POLICY IF EXISTS "Users can update their own courses" ON public.courses;
DROP POLICY IF EXISTS "Users can delete their own courses" ON public.courses;

-- 创建新策略 (强制 user_id 匹配)

-- Tasks Policies
CREATE POLICY "Users can view their own tasks" ON public.tasks 
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own tasks" ON public.tasks 
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tasks" ON public.tasks 
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tasks" ON public.tasks 
    FOR DELETE USING (auth.uid() = user_id);

-- Courses Policies
CREATE POLICY "Users can view their own courses" ON public.courses 
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own courses" ON public.courses 
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own courses" ON public.courses 
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own courses" ON public.courses 
    FOR DELETE USING (auth.uid() = user_id);
