-- ⚠️ 警告：此脚本将删除所有数据和表结构！请谨慎操作！

-- 1. 删除视图
DROP VIEW IF EXISTS daily_leaderboard;

-- 2. 删除表 (注意顺序：先删除依赖表)
DROP TABLE IF EXISTS study_logs CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS app_releases CASCADE;

-- 3. 删除函数和触发器
-- (表被删除时触发器会自动删除，无需手动删除 on_study_log_created)
DROP FUNCTION IF EXISTS update_task_duration;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS create_user_profile;

-- 4. 重新创建表结构 (合并自 supabase_schema.sql 和 supabase_schedule.sql)

-- === 用户资料表 ===
create table if not exists user_profiles (
  id uuid primary key references auth.users on delete cascade,
  username varchar(50) unique,
  username_updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table user_profiles enable row level security;

create policy "Anyone can view profiles" on user_profiles for select using (true);
create policy "Users can update own profile" on user_profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on user_profiles for insert with check (auth.uid() = id);

-- 自动创建用户资料触发器
create or replace function create_user_profile()
returns trigger as $$
begin
  insert into user_profiles (id)
  values (new.id)
  on conflict do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure create_user_profile();

-- === 任务表 ===
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  status text default 'pending',
  priority text default 'medium',
  due_date timestamp with time zone,
  estimated_duration int,
  actual_duration int default 0,
  start_time timestamp with time zone, -- 确保包含此字段
  color text, -- 添加颜色字段
  created_at timestamp with time zone default now()
);
alter table tasks enable row level security;

create policy "Users can view own tasks" on tasks for select using (auth.uid() = user_id);
create policy "Users can insert own tasks" on tasks for insert with check (auth.uid() = user_id);
create policy "Users can update own tasks" on tasks for update using (auth.uid() = user_id);
create policy "Users can delete own tasks" on tasks for delete using (auth.uid() = user_id);

-- === 课程表 ===
create table if not exists courses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  location text,
  day_of_week int not null, -- 1-7
  start_time text not null, -- "HH:mm"
  end_time text not null,   -- "HH:mm"
  color text,
  created_at timestamp with time zone default now()
);
alter table courses enable row level security;

create policy "Users can view own courses" on courses for select using (auth.uid() = user_id);
create policy "Users can insert own courses" on courses for insert with check (auth.uid() = user_id);
create policy "Users can update own courses" on courses for update using (auth.uid() = user_id);
create policy "Users can delete own courses" on courses for delete using (auth.uid() = user_id);

-- === 学习日志表 ===
create table if not exists study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  duration int not null,
  task_id bigint references tasks(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table study_logs enable row level security;

create policy "Users can insert their own logs" on study_logs for insert with check (auth.uid() = user_id);
create policy "Everyone can view logs" on study_logs for select using (true);

-- 自动更新任务时长触发器
create or replace function update_task_duration()
returns trigger as $$
begin
  if new.task_id is not null then
    update tasks
    set actual_duration = actual_duration + new.duration
    where id = new.task_id;
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_study_log_created
  after insert on study_logs
  for each row execute procedure update_task_duration();

-- === 应用版本表 (可选) ===
create table if not exists app_releases (
  id bigint generated by default as identity primary key,
  version text not null,
  platform text not null, -- 'ios' or 'android'
  download_url text not null,
  description text,
  force_update boolean default false,
  created_at timestamp with time zone default now()
);
alter table app_releases enable row level security;
create policy "Anyone can read releases" on app_releases for select using (true);

-- === 排行榜视图 ===
create view daily_leaderboard as
select 
  user_id,
  sum(duration) as total_duration
from study_logs
where created_at > current_date
group by user_id
order by total_duration desc;
