-- 创建应用版本控制表
create table if not exists app_releases (
  id bigint generated by default as identity primary key,
  version text not null, -- 例如 '1.0.1'
  build_number int, -- 例如 101
  platform text not null check (platform in ('ios', 'android')),
  download_url text not null,
  description text,
  force_update boolean default false,
  created_at timestamp with time zone default now()
);

-- 开启 RLS
alter table app_releases enable row level security;

-- 允许所有人读取版本信息 (无需登录即可检查更新)
create policy "Anyone can read app releases"
  on app_releases for select
  using (true);

-- 仅允许管理员插入/更新/删除 (这里假设只有 service_role 或特定用户可以操作，或者您可以根据需要调整)
-- 暂时为了方便，如果您在 Supabase Dashboard 操作，不需要额外 Policy，因为 Dashboard 是超级管理员权限。
-- 如果您有后台管理系统，需要添加相应的 Policy。
