-- Create courses table
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  location text,
  day_of_week int not null check (day_of_week between 1 and 7), -- 1=Monday, 7=Sunday
  start_time time not null,
  end_time time not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.courses enable row level security;

-- Create policies
create policy "Users can view their own courses"
  on public.courses for select
  using (auth.uid() = user_id);

create policy "Users can insert their own courses"
  on public.courses for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own courses"
  on public.courses for update
  using (auth.uid() = user_id);

create policy "Users can delete their own courses"
  on public.courses for delete
  using (auth.uid() = user_id);
