-- 1. 创建用于存储 API Key 的表 (如果不存在)
CREATE TABLE IF NOT EXISTS app_secrets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 开启行级安全 (RLS)
ALTER TABLE app_secrets ENABLE ROW LEVEL SECURITY;

-- 3. 创建访问策略：允许所有用户(包括未登录用户)读取此表
-- 注意：因为 DeepSeek Key 本质上需要在前端使用，所以这里设置为公开读取是符合当前架构的
DROP POLICY IF EXISTS "Allow public read access" ON app_secrets;
CREATE POLICY "Allow public read access" ON app_secrets FOR SELECT USING (true);

-- 4. 插入你的 API Keys (请替换下方的占位符为你的真实 Key)
-- 如果你已经添加过，这行可以忽略，或者用来更新
INSERT INTO app_secrets (name, value)
VALUES 
  ('DEEPSEEK_API_KEY', 'sk-你的DeepSeek密钥'),
  ('BAIDU_API_KEY', '你的百度API Key'),
  ('BAIDU_SECRET_KEY', '你的百度Secret Key')
ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value;

