-- 1. 创建 user_profiles 表 (用户资料)
create table if not exists user_profiles (
  id uuid primary key references auth.users on delete cascade,
  username varchar(50) unique,
  username_updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 开启 RLS
alter table user_profiles enable row level security;

-- 3. 允许用户查看任何用户的资料 (用于排行榜)
drop policy if exists "Anyone can view profiles" on user_profiles;
create policy "Anyone can view profiles"
  on user_profiles for select
  using (true);

-- 4. 允许用户更新自己的资料
drop policy if exists "Users can update own profile" on user_profiles;
create policy "Users can update own profile"
  on user_profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- 5. 允许用户插入自己的资料
drop policy if exists "Users can insert own profile" on user_profiles;
create policy "Users can insert own profile"
  on user_profiles for insert
  with check (auth.uid() = id);

-- 6. 创建用户时自动创建资料记录
create or replace function create_user_profile()
returns trigger as $$
begin
  insert into user_profiles (id)
  values (new.id)
  on conflict do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure create_user_profile();

-- 7. 创建 study_logs 表
create table if not exists study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  duration int not null, -- 专注时长（秒）
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. 开启 RLS (Row Level Security) 安全策略
alter table study_logs enable row level security;

-- 9. 允许用户插入自己的数据
drop policy if exists "Users can insert their own logs" on study_logs;
create policy "Users can insert their own logs"
  on study_logs for insert
  with check (auth.uid() = user_id);

-- 10. 允许所有人查看数据 (为了排行榜)
drop policy if exists "Everyone can view logs" on study_logs;
create policy "Everyone can view logs"
  on study_logs for select
  using (true);

-- 11. 为所有已存在的用户创建资料记录
insert into user_profiles (id)
select id from auth.users
on conflict do nothing;

-- 12. (可选) 创建一个视图来加速排行榜查询
-- 这个视图会聚合每个用户当天的总专注时长
drop view if exists daily_leaderboard;
create view daily_leaderboard as
select 
  user_id,
  sum(duration) as total_duration
from study_logs
where created_at > current_date
group by user_id
order by total_duration desc;

-- 13. 更新 tasks 表结构 (请在 Supabase SQL 编辑器中运行)
-- alter table tasks add column start_time timestamp with time zone;
