-- 1. 创建 tasks 表
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  status text default 'pending', -- pending, in_progress, completed
  priority text default 'medium', -- high, medium, low
  due_date timestamp with time zone,
  estimated_duration int, -- 预计秒数
  actual_duration int default 0, -- 实际投入秒数 (自动累加)
  created_at timestamp with time zone default now()
);

-- 2. 开启 RLS
alter table tasks enable row level security;

-- 3. 允许用户对自己任务的增删改查
create policy "Users can view own tasks" on tasks for select using (auth.uid() = user_id);
create policy "Users can insert own tasks" on tasks for insert with check (auth.uid() = user_id);
create policy "Users can update own tasks" on tasks for update using (auth.uid() = user_id);
create policy "Users can delete own tasks" on tasks for delete using (auth.uid() = user_id);

-- 4. 修改 study_logs 表，添加 task_id 关联
alter table study_logs 
add column if not exists task_id bigint references tasks(id) on delete set null;

-- 5. 创建触发器：当 study_logs 插入时，自动更新对应 task 的 actual_duration
create or replace function update_task_duration()
returns trigger as $$
begin
  if new.task_id is not null then
    update tasks
    set actual_duration = actual_duration + new.duration
    where id = new.task_id;
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_study_log_created on study_logs;
create trigger on_study_log_created
  after insert on study_logs
  for each row execute procedure update_task_duration();
