-- Open-source safe setup template
-- This file intentionally contains NO real API keys.

-- 1) Secrets table for runtime key retrieval
CREATE TABLE IF NOT EXISTS public.app_secrets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.app_secrets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON public.app_secrets;
CREATE POLICY "Allow public read access"
ON public.app_secrets
FOR SELECT
USING (true);

-- 2) Tasks recurring columns (keep schema in sync with app)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS is_recurring boolean DEFAULT false;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS recurring_days integer[] DEFAULT '{}';

-- 3) Optional: insert placeholders ONLY
-- Replace <...> before executing in your own environment.
INSERT INTO public.app_secrets (name, value)
VALUES
  ('DEEPSEEK_API_KEY', '<YOUR_DEEPSEEK_API_KEY>'),
  ('BAIDU_API_KEY', '<YOUR_BAIDU_API_KEY>'),
  ('BAIDU_SECRET_KEY', '<YOUR_BAIDU_SECRET_KEY>')
ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value;
